### ISSUE TITLE
Question: Funtionality Lost between 0.3.3 and 1.x

### ISSUE THREAD

**Issue by valoricDe** [creativetimofficial/material-tailwind#179]
Hi there,
I'm currently migrating from 0.3.3 to 1.1.0 and realized that there is some stuff missing which was there before. Some of them easily replaceable (InputIcon) and others with a bit more work.
Like the NavbarBrand, NavbarInput, Nav (Sidepanel) etc. I just wonder why. 

Thanks have a good day.

**Comment by sajadevo** [comment]
Hi @valoricDe,

The v0.3.3 was not the official version and on the v1 we start to make the components more reusable and flexible the `InputIcon` is dropped and you can use the `icon` prop for the `Input` component instead and the `Navbar` components was dropped because now the input and other components are totally customizable and we you don't need to have those components, please take a look to the documentation of the project for a better knowledge.

Cheers,
Sajad
