### ISSUE TITLE
setup doesn't work with npm workspaces

### ISSUE THREAD

**Issue by hesxenon** [creativetimofficial/material-tailwind#213]
Hey, first of all thanks for all your work, I'm really looking forward to using this lib.

This wasn't particularly hard to solve once I looked into the code but the following should either be documented or you might want to find a more involved solution.

Given a setup where the tailwind config is not located at the same level as the node_modules (as is the case with npm workspaces) `withMT` will yield the wrong paths.

Maybe you could check where `@material-tailwind` is actually installed so the paths could be computed?

**Comment by sajadevo** [comment]
Hey @hesxenon,

I've added a section related to tailwind config for @material-tailwind/react in monorepos/workspaces this will help people who're using the library with a monorepos/workspaces, I can't add any specific path for monorepos/workspaces because it will be different on different projects.

Here are the links:
1. Next.js: [https://www.material-tailwind.com/docs/react/guide/next#with-monorepo](https://www.material-tailwind.com/docs/react/guide/next#with-monorepo)
2. CRA: [https://www.material-tailwind.com/docs/react/guide/cra#with-monorepo](https://www.material-tailwind.com/docs/react/guide/cra#with-monorepo)
3. Remix: [https://www.material-tailwind.com/docs/react/guide/remix#with-monorepo](https://www.material-tailwind.com/docs/react/guide/remix#with-monorepo)
4. Vite: [https://www.material-tailwind.com/docs/react/guide/vite#with-monorepo](https://www.material-tailwind.com/docs/react/guide/vite#with-monorepo)

Cheers,
Sajad

**Comment by randallhunt** [comment]
This was easy enough to fix.  I've forked and [made a pull request](https://github.com/creativetimofficial/material-tailwind/pull/271).

**Comment by sajadevo** [comment]
@randallhunt thanks for your contribution I really appreciate your work I'll test it and make sure it's working for all cases we need and then merge it with the next update of the library.

Cheers,
Sajad

**Comment by zacker330** [comment]
I got the same issue while I using pnpm workspace:
- material-tailwind: 2.0.5
- tailwindcss: 3.3.3
- pnpm: 8.6.12
- react: 18.2.0
- nodejs: v16.15.0

The content of tailwind.config.js is following:

```javascript
const withMT = require("@material-tailwind/react/utils/withMT");

/** @type {import('tailwindcss').Config} */
module.exports = withMT({
  content: [
    "./public/index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
    },
  },
  plugins: [],
});
```
Is there any solution for that? Thanks.
