### ISSUE TITLE
Support for NextJS 13 and server components

### ISSUE THREAD

**Issue by chris-hinds** [creativetimofficial/material-tailwind#258]
Will Material Tailwind get full support for nextJS 13 and Reacts server components? To utilise server components and MTW we would need to make every component as a client component.

**Comment by sajadevo** [comment]
Hey @chris-hinds,

For sure we'll make it available but it won't happen soon because first we need to make the library as much stable as we can.

Cheers,
Sajad

**Comment by deadlyicon** [comment]
@sajadevo Is there any path to removing the use of `createContext`? If we can manage that it should be easy to get this working in next13's appDir

**Comment by sajadevo** [comment]
@chris-hinds and @jaredatron since the library is using the context api of react here is the solution for using it with Next.js 13 appDir: 

1. On the `app/layout.tsx` put the following code:
```tsx
"use client";
import "./globals.css";
import { ThemeProvider } from "@material-tailwind/react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <ThemeProvider>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
```

2. Then on the pages that you want to have the components from @material-tailwind/react use the `'use client'` at the top of the file.

I'll try to make the components do this by default but for now you can go with this solution.

Cheers,
Sajad

**Comment by sebkasanzew** [comment]
@sajadevo Do your changes also fix this error?

<img width="580" alt="image" src="https://user-images.githubusercontent.com/2511905/218104595-e8ab805e-c0fb-4247-b070-1fe04ec0a144.png">

<details>
<summary>
    Error text:
  </summary>
`Warning: ThemeProvider: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at ThemeProvider (webpack-internal:///(app-client)/./node_modules/@material-tailwind/react/context/theme.js:1:2369)`
</details>

Or should I open a new issue for this?

**Comment by sajadevo** [comment]
> @sajadevo Do your changes also fix this error?
> 
> 
> 
> <img width="580" alt="image" src="https://user-images.githubusercontent.com/2511905/218104595-e8ab805e-c0fb-4247-b070-1fe04ec0a144.png">
> 
> 
> 
> <details>
> 
> <summary>
> 
>     Error text:
> 
>   </summary>
> 
> <pre>
> 
> Warning: ThemeProvider: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
> 
>     at ThemeProvider (webpack-internal:///(app-client)/./node_modules/@material-tailwind/react/context/theme.js:1:2369)
> 
> </pre>
> 
> </details>
> 
> 
> 
> Or should I open a new issue for this?

Already fixed @sebkasanzew 🙌🏻

**Comment by sebkasanzew** [comment]
Hi, I want to ask about the time frame, when a version with this fix will be released, because I want to start to work on a prototype with Next.js 13 appDir tomorrow.

Or is there already a beta release, or something, which I am missing?
I also don't see a WIP-branch. Can I help with the development?

**Comment by sajadevo** [comment]
Hey @jaredatron @chris-hinds @sebkasanzew 

I've added a complete guide about this issue on the documentation since this is a UI library and uses lots of interactivities we can get rid to the React Context API but the way I've mentioned on the documentation will give you a smooth work flow.

[https://www.material-tailwind.com/docs/react/guide/next#with-server-components](https://www.material-tailwind.com/docs/react/guide/next#with-server-components) 

Cheers,
Sajad

**Comment by olee** [comment]
I tried setting this up with a new project just now and cannot get it to work.
Where should I add the ThemeProvider to the project because I have no `pages/_app.tsx`?

**Comment by chris-hinds** [comment]
> I tried setting this up with a new project just now and cannot get it to work. Where should I add the ThemeProvider to the project because I have no `pages/_app.tsx`? Also, I'm getting this error: `Prop `className` did not match. Server: "__className_0ec1f4 vsc-initialized" Client: "__className_0ec1f4"`
> 
> I think the section for nextjs 13 should be extended a bit more to clarify these details 👍

The Theme Provider would now sit in your top level Layout file.

**Comment by tae100k** [comment]
With the exact same code you provided : https://github.com/creativetimofficial/material-tailwind/issues/258#issuecomment-1425192149

I'm getting a type error

<img width="764" alt="Screenshot 2024-05-18 at 11 31 52 PM" src="https://github.com/creativetimofficial/material-tailwind/assets/78027252/f3a4aff4-f696-43b8-8a24-50fbc002b606">

**Comment by fhfournier** [comment]
I can't use the "use client" on the RootLayout. So this is the only way I can use your library :\ 

If I follow your doc with next14 this is what I've got

![image](https://github.com/user-attachments/assets/436dcf9f-16c3-44ac-8c32-d59416a71bb9)

```
`import { ThemeProvider } from "@material-tailwind/react";

import "@/app/globals.css"

export default function RootLayout({ children }) {
  return (
    <html>
    <body>
      <ThemeProvider>
        {children}
      </ThemeProvider>
    </body>
    </html>
```
