### ISSUE TITLE
Speed Dial Action

### ISSUE THREAD

**Issue by sseekamp0** [creativetimofficial/material-tailwind#443]
Hello,
I'm attempting to use the speed dial action component, however can't find a way to access an onClick event. It seems that the component is defaulting to onSubmit when clicked... is there a way to have the SpeedDialAction function like a button? Could you provide details on the props that are allowed for the component?

**Comment by zxul767** [comment]
I took a cursory look at the source code and I couldn't find any callbacks like `onClick`.

There is an imperfect workaround, which is to add some element that does accept `onClick` (e.g., `span`) as a children of `SpeedDialAction`, but it doesn't solve the problem completely, since it only triggers the callback when clicking exactly on it (a bit of a UX letdown)

**Comment by zxul767** [comment]
Actually, there is a much better workaround: just wrap `SpeedDialContent` in a `<div onClick={...}> ...</div>`.

I'd rather not have to add superfluous `div`s but as a workaround this will do for now.

**Comment by sajadevo** [comment]
This issue is fixed on v2.1.2
